# Generated by Django 4.2.3 on 2024-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/category'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
